### ISSUE TITLE
 No module named 'labelmodels'

### ISSUE THREAD

**Issue by Ataullakhan** [megagonlabs/tagruler#2]
i am trying to run the Tool, but it seems like there some functions or models are missing can any one help me
with this.

in line :    server/verifier/label_models.py", line 1
this import:     from labelmodels.label_model import ClassConditionalLabelModel, LearningConfig, init_random
error:    ModuleNotFoundError: No module named 'labelmodels'

**Comment by skywalker5** [comment]
Have you run
`pip install -r requirements.txt` ?
'labelmodels' should be installed after running it.

**Comment by Ataullakhan** [comment]
thanks for the reply.
but there is no package mantion in 'requirements.txt' as 'labelmodels'.
its not even there in pypi - pip.

**Comment by Ataullakhan** [comment]
> Have you run
> `pip install -r requirements.txt` ?
> 'labelmodels' should be installed after running it.

thanks for the reply.
but there is no package mantion in 'requirements.txt' as 'labelmodels'.
its not even there in pypi - pip.
