### ISSUE TITLE
How to create .nlp file ?

### ISSUE THREAD

**Issue by sakshi20040** [megagonlabs/tagruler#3]
We have tried to create .nlp file for our own dataset using DataSetReader of  allennlp.  But still we are not able to run the application using the files(.csv,  .bert, .elmo, .sbert, .nlp) generated on our own dataset.
Here is the code for the same.  

 #**start of the code**

  from typing import Dict, Iterable, List 
  from allennlp.data import DatasetReader, Instance
  from allennlp.data.fields import Field, LabelField, TextField
  from allennlp.data.token_indexers import TokenIndexer, SingleIdTokenIndexer
  from allennlp.data.tokenizers import Token, Tokenizer, WhitespaceTokenizer
  
  import re
  import spacy
  from spacy.tokenizer import Tokenizer
  nlp = spacy.load('en_core_web_sm')`

class ClassificationTsvReader(DatasetReader):
    def __init__( self,   tokenizer: Tokenizer = None, token_indexers: Dict[str, TokenIndexer] = None, max_tokens: int = None, **kwargs ):
        super().__init__(**kwargs)
        self.tokenizer = tokenizer or WhitespaceTokenizer()
        self.token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        self.max_tokens = max_tokens

    def text_to_instance(self, text: str, label: str = None) -> Instance:
        tokens = self.tokenizer.tokenize(text)
        if self.max_tokens:
            tokens = tokens[: self.max_tokens]
        text_field = TextField(tokens, self.token_indexers)
        fields: Dict[str, Field] = {"text": text_field}
        if label:
            fields["label"] = LabelField(label)
        yield Instance(fields)

df = pd.read_csv("/content/processed.csv")

instances_arr = np.empty(86,dtype=object)

for i in range(0,len(df)):
  temp_arr =  np.empty(1,dtype=object)
  text = df["text"][i]
  label = ""
  instance = list(reader.text_to_instance(text, label))[0]
  temp_arr[0] = instance
  instances_arr[i] = temp_arr

finalList = []
finalList.append(instances_arr)

#**end of the code**

**Comment by skywalker5** [comment]
Apologies for late response.
I'm currently writing some sample codes to create .nlp file. I'll post the code ASAP.
Thank you for your interest!

**Comment by kasuba-badri-vishal** [comment]
Hi @skywalker5 @sakshi20040 ,
Is there any progress here in generating .nlp file and preprocessing custom datasets?

**Comment by skywalker5** [comment]
I updated some codes to process custom datasets.
Please check 'tagruler/server/datasets/data_process_example' folder.
