### ISSUE TITLE
Custom dataset issue

### ISSUE THREAD

**Issue by kasuba-badri-vishal** [megagonlabs/tagruler#5]
I have used my own custom dataset as per the instructions provided in the README file. But yet facing issue. Model is stuck here as shown for infinity. 
![image](https://user-images.githubusercontent.com/40017320/129174696-13e5d89c-dfe9-40f2-94b1-8e3e94cc1e9b.png)

**Comment by skywalker5** [comment]
I updated some codes to process custom datasets.
Please check 'tagruler/server/datasets/data_process_example' folder.
